/* datamodelH.h
   Generated by gSOAP 2.7.9l from datamodel_h.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef datamodelH_H
#define datamodelH_H
#include "datamodelStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);
SOAP_FMAC5 std::string * SOAP_FMAC6 soap_new_std__string(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__string(struct soap*, std::string*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__genmech__mech
#define SOAP_TYPE__genmech__mech (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__genmech__mech(struct soap*, const char*, int, const _genmech__mech *, const char*);
SOAP_FMAC3 _genmech__mech * SOAP_FMAC4 soap_get__genmech__mech(struct soap*, _genmech__mech *, const char*, const char*);
SOAP_FMAC3 _genmech__mech * SOAP_FMAC4 soap_in__genmech__mech(struct soap*, const char*, _genmech__mech *, const char*);
SOAP_FMAC5 _genmech__mech * SOAP_FMAC6 soap_new__genmech__mech(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__genmech__mech(struct soap*, _genmech__mech*);
SOAP_FMAC3 _genmech__mech * SOAP_FMAC4 soap_instantiate__genmech__mech(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__genmech__mech(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_genmech__mesh
#define SOAP_TYPE_genmech__mesh (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_genmech__mesh(struct soap*, const char*, int, const genmech__mesh *, const char*);
SOAP_FMAC3 genmech__mesh * SOAP_FMAC4 soap_get_genmech__mesh(struct soap*, genmech__mesh *, const char*, const char*);
SOAP_FMAC3 genmech__mesh * SOAP_FMAC4 soap_in_genmech__mesh(struct soap*, const char*, genmech__mesh *, const char*);
SOAP_FMAC5 genmech__mesh * SOAP_FMAC6 soap_new_genmech__mesh(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_genmech__mesh(struct soap*, genmech__mesh*);
SOAP_FMAC3 genmech__mesh * SOAP_FMAC4 soap_instantiate_genmech__mesh(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_genmech__mesh(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_genmech__torso
#define SOAP_TYPE_genmech__torso (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_genmech__torso(struct soap*, const char*, int, const genmech__torso *, const char*);
SOAP_FMAC3 genmech__torso * SOAP_FMAC4 soap_get_genmech__torso(struct soap*, genmech__torso *, const char*, const char*);
SOAP_FMAC3 genmech__torso * SOAP_FMAC4 soap_in_genmech__torso(struct soap*, const char*, genmech__torso *, const char*);
SOAP_FMAC5 genmech__torso * SOAP_FMAC6 soap_new_genmech__torso(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_genmech__torso(struct soap*, genmech__torso*);
SOAP_FMAC3 genmech__torso * SOAP_FMAC4 soap_instantiate_genmech__torso(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_genmech__torso(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_genmech__equSlot
#define SOAP_TYPE_genmech__equSlot (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_genmech__equSlot(struct soap*, const char*, int, const genmech__equSlot *, const char*);
SOAP_FMAC3 genmech__equSlot * SOAP_FMAC4 soap_get_genmech__equSlot(struct soap*, genmech__equSlot *, const char*, const char*);
SOAP_FMAC3 genmech__equSlot * SOAP_FMAC4 soap_in_genmech__equSlot(struct soap*, const char*, genmech__equSlot *, const char*);
SOAP_FMAC5 genmech__equSlot * SOAP_FMAC6 soap_new_genmech__equSlot(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_genmech__equSlot(struct soap*, genmech__equSlot*);
SOAP_FMAC3 genmech__equSlot * SOAP_FMAC4 soap_instantiate_genmech__equSlot(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_genmech__equSlot(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_genmech__equSlots
#define SOAP_TYPE_genmech__equSlots (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_genmech__equSlots(struct soap*, const char*, int, const genmech__equSlots *, const char*);
SOAP_FMAC3 genmech__equSlots * SOAP_FMAC4 soap_get_genmech__equSlots(struct soap*, genmech__equSlots *, const char*, const char*);
SOAP_FMAC3 genmech__equSlots * SOAP_FMAC4 soap_in_genmech__equSlots(struct soap*, const char*, genmech__equSlots *, const char*);
SOAP_FMAC5 genmech__equSlots * SOAP_FMAC6 soap_new_genmech__equSlots(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_genmech__equSlots(struct soap*, genmech__equSlots*);
SOAP_FMAC3 genmech__equSlots * SOAP_FMAC4 soap_instantiate_genmech__equSlots(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_genmech__equSlots(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_genmech__design
#define SOAP_TYPE_genmech__design (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_genmech__design(struct soap*, const char*, int, const genmech__design *, const char*);
SOAP_FMAC3 genmech__design * SOAP_FMAC4 soap_get_genmech__design(struct soap*, genmech__design *, const char*, const char*);
SOAP_FMAC3 genmech__design * SOAP_FMAC4 soap_in_genmech__design(struct soap*, const char*, genmech__design *, const char*);
SOAP_FMAC5 genmech__design * SOAP_FMAC6 soap_new_genmech__design(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_genmech__design(struct soap*, genmech__design*);
SOAP_FMAC3 genmech__design * SOAP_FMAC4 soap_instantiate_genmech__design(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_genmech__design(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_genmech__stats
#define SOAP_TYPE_genmech__stats (7)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_genmech__stats(struct soap*, const char*, int, const genmech__stats *, const char*);
SOAP_FMAC3 genmech__stats * SOAP_FMAC4 soap_get_genmech__stats(struct soap*, genmech__stats *, const char*, const char*);
SOAP_FMAC3 genmech__stats * SOAP_FMAC4 soap_in_genmech__stats(struct soap*, const char*, genmech__stats *, const char*);
SOAP_FMAC5 genmech__stats * SOAP_FMAC6 soap_new_genmech__stats(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_genmech__stats(struct soap*, genmech__stats*);
SOAP_FMAC3 genmech__stats * SOAP_FMAC4 soap_instantiate_genmech__stats(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_genmech__stats(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Fault * SOAP_FMAC6 soap_new_SOAP_ENV__Fault(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Reason * SOAP_FMAC6 soap_new_SOAP_ENV__Reason(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Detail * SOAP_FMAC6 soap_new_SOAP_ENV__Detail(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Code * SOAP_FMAC6 soap_new_SOAP_ENV__Code(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Header * SOAP_FMAC6 soap_new_SOAP_ENV__Header(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTogenmech__mesh
#define SOAP_TYPE_PointerTogenmech__mesh (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTogenmech__mesh(struct soap*, genmech__mesh *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTogenmech__mesh(struct soap*, genmech__mesh *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTogenmech__mesh(struct soap*, const char *, int, genmech__mesh *const*, const char *);
SOAP_FMAC3 genmech__mesh ** SOAP_FMAC4 soap_get_PointerTogenmech__mesh(struct soap*, genmech__mesh **, const char*, const char*);
SOAP_FMAC3 genmech__mesh ** SOAP_FMAC4 soap_in_PointerTogenmech__mesh(struct soap*, const char*, genmech__mesh **, const char*);

#ifndef SOAP_TYPE_PointerTogenmech__design
#define SOAP_TYPE_PointerTogenmech__design (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTogenmech__design(struct soap*, genmech__design *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTogenmech__design(struct soap*, genmech__design *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTogenmech__design(struct soap*, const char *, int, genmech__design *const*, const char *);
SOAP_FMAC3 genmech__design ** SOAP_FMAC4 soap_get_PointerTogenmech__design(struct soap*, genmech__design **, const char*, const char*);
SOAP_FMAC3 genmech__design ** SOAP_FMAC4 soap_in_PointerTogenmech__design(struct soap*, const char*, genmech__design **, const char*);

#ifndef SOAP_TYPE_PointerTogenmech__stats
#define SOAP_TYPE_PointerTogenmech__stats (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTogenmech__stats(struct soap*, genmech__stats *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTogenmech__stats(struct soap*, genmech__stats *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTogenmech__stats(struct soap*, const char *, int, genmech__stats *const*, const char *);
SOAP_FMAC3 genmech__stats ** SOAP_FMAC4 soap_get_PointerTogenmech__stats(struct soap*, genmech__stats **, const char*, const char*);
SOAP_FMAC3 genmech__stats ** SOAP_FMAC4 soap_in_PointerTogenmech__stats(struct soap*, const char*, genmech__stats **, const char*);

#ifndef SOAP_TYPE_PointerTogenmech__equSlot
#define SOAP_TYPE_PointerTogenmech__equSlot (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTogenmech__equSlot(struct soap*, genmech__equSlot *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTogenmech__equSlot(struct soap*, genmech__equSlot *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTogenmech__equSlot(struct soap*, const char *, int, genmech__equSlot *const*, const char *);
SOAP_FMAC3 genmech__equSlot ** SOAP_FMAC4 soap_get_PointerTogenmech__equSlot(struct soap*, genmech__equSlot **, const char*, const char*);
SOAP_FMAC3 genmech__equSlot ** SOAP_FMAC4 soap_in_PointerTogenmech__equSlot(struct soap*, const char*, genmech__equSlot **, const char*);

#ifndef SOAP_TYPE_PointerTogenmech__equSlots
#define SOAP_TYPE_PointerTogenmech__equSlots (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTogenmech__equSlots(struct soap*, genmech__equSlots *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTogenmech__equSlots(struct soap*, genmech__equSlots *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTogenmech__equSlots(struct soap*, const char *, int, genmech__equSlots *const*, const char *);
SOAP_FMAC3 genmech__equSlots ** SOAP_FMAC4 soap_get_PointerTogenmech__equSlots(struct soap*, genmech__equSlots **, const char*, const char*);
SOAP_FMAC3 genmech__equSlots ** SOAP_FMAC4 soap_in_PointerTogenmech__equSlots(struct soap*, const char*, genmech__equSlots **, const char*);

#ifndef SOAP_TYPE_PointerTogenmech__torso
#define SOAP_TYPE_PointerTogenmech__torso (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTogenmech__torso(struct soap*, genmech__torso *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTogenmech__torso(struct soap*, genmech__torso *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTogenmech__torso(struct soap*, const char *, int, genmech__torso *const*, const char *);
SOAP_FMAC3 genmech__torso ** SOAP_FMAC4 soap_get_PointerTogenmech__torso(struct soap*, genmech__torso **, const char*, const char*);
SOAP_FMAC3 genmech__torso ** SOAP_FMAC4 soap_in_PointerTogenmech__torso(struct soap*, const char*, genmech__torso **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTogenmech__equSlot
#define SOAP_TYPE_std__vectorTemplateOfPointerTogenmech__equSlot (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerTogenmech__equSlot(struct soap*, std::vector<genmech__equSlot * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerTogenmech__equSlot(struct soap*, const std::vector<genmech__equSlot * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerTogenmech__equSlot(struct soap*, const char*, int, const std::vector<genmech__equSlot * >*, const char*);
SOAP_FMAC3 std::vector<genmech__equSlot * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerTogenmech__equSlot(struct soap*, const char*, std::vector<genmech__equSlot * >*, const char*);
SOAP_FMAC5 std::vector<genmech__equSlot * > * SOAP_FMAC6 soap_new_std__vectorTemplateOfPointerTogenmech__equSlot(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__vectorTemplateOfPointerTogenmech__equSlot(struct soap*, std::vector<genmech__equSlot * >*);
SOAP_FMAC3 std::vector<genmech__equSlot * > * SOAP_FMAC4 soap_instantiate_std__vectorTemplateOfPointerTogenmech__equSlot(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerTogenmech__equSlot(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

/* End of datamodelH.h */
